ATTACH TABLE _ UUID '4b77ab37-f2f9-430b-9cf2-c83096ba5cc6'
(
    `ts_bucket_start` UInt64 CODEC(DoubleDelta, LZ4),
    `resource_fingerprint` String CODEC(ZSTD(1)),
    `timestamp` DateTime64(9) CODEC(DoubleDelta, LZ4),
    `trace_id` FixedString(32) CODEC(ZSTD(1)),
    `span_id` String CODEC(ZSTD(1)),
    `trace_state` String CODEC(ZSTD(1)),
    `parent_span_id` String CODEC(ZSTD(1)),
    `flags` UInt32 CODEC(T64, ZSTD(1)),
    `name` LowCardinality(String) CODEC(ZSTD(1)),
    `kind` Int8 CODEC(T64, ZSTD(1)),
    `kind_string` String CODEC(ZSTD(1)),
    `duration_nano` UInt64 CODEC(T64, ZSTD(1)),
    `status_code` Int16 CODEC(T64, ZSTD(1)),
    `status_message` String CODEC(ZSTD(1)),
    `status_code_string` String CODEC(ZSTD(1)),
    `attributes_string` Map(LowCardinality(String), String) CODEC(ZSTD(1)),
    `attributes_number` Map(LowCardinality(String), Float64) CODEC(ZSTD(1)),
    `attributes_bool` Map(LowCardinality(String), Bool) CODEC(ZSTD(1)),
    `resources_string` Map(LowCardinality(String), String) CODEC(ZSTD(1)),
    `events` Array(String) CODEC(ZSTD(2)),
    `links` String CODEC(ZSTD(1)),
    `response_status_code` LowCardinality(String) CODEC(ZSTD(1)),
    `external_http_url` LowCardinality(String) CODEC(ZSTD(1)),
    `http_url` LowCardinality(String) CODEC(ZSTD(1)),
    `external_http_method` LowCardinality(String) CODEC(ZSTD(1)),
    `http_method` LowCardinality(String) CODEC(ZSTD(1)),
    `http_host` LowCardinality(String) CODEC(ZSTD(1)),
    `db_name` LowCardinality(String) CODEC(ZSTD(1)),
    `db_operation` LowCardinality(String) CODEC(ZSTD(1)),
    `has_error` Bool CODEC(T64, ZSTD(1)),
    `is_remote` LowCardinality(String) CODEC(ZSTD(1)),
    `resource_string_service$$name` LowCardinality(String) DEFAULT resources_string['service.name'] CODEC(ZSTD(1)),
    `attribute_string_http$$route` LowCardinality(String) DEFAULT attributes_string['http.route'] CODEC(ZSTD(1)),
    `attribute_string_messaging$$system` LowCardinality(String) DEFAULT attributes_string['messaging.system'] CODEC(ZSTD(1)),
    `attribute_string_messaging$$operation` LowCardinality(String) DEFAULT attributes_string['messaging.operation'] CODEC(ZSTD(1)),
    `attribute_string_db$$system` LowCardinality(String) DEFAULT attributes_string['db.system'] CODEC(ZSTD(1)),
    `attribute_string_rpc$$system` LowCardinality(String) DEFAULT attributes_string['rpc.system'] CODEC(ZSTD(1)),
    `attribute_string_rpc$$service` LowCardinality(String) DEFAULT attributes_string['rpc.service'] CODEC(ZSTD(1)),
    `attribute_string_rpc$$method` LowCardinality(String) DEFAULT attributes_string['rpc.method'] CODEC(ZSTD(1)),
    `attribute_string_peer$$service` LowCardinality(String) DEFAULT attributes_string['peer.service'] CODEC(ZSTD(1)),
    `traceID` FixedString(32) ALIAS trace_id,
    `spanID` String ALIAS span_id,
    `parentSpanID` String ALIAS parent_span_id,
    `spanKind` String ALIAS kind_string,
    `durationNano` UInt64 ALIAS duration_nano,
    `statusCode` Int16 ALIAS status_code,
    `statusMessage` String ALIAS status_message,
    `statusCodeString` String ALIAS status_code_string,
    `references` String ALIAS links,
    `responseStatusCode` LowCardinality(String) ALIAS response_status_code,
    `externalHttpUrl` LowCardinality(String) ALIAS external_http_url,
    `httpUrl` LowCardinality(String) ALIAS http_url,
    `externalHttpMethod` LowCardinality(String) ALIAS external_http_method,
    `httpMethod` LowCardinality(String) ALIAS http_method,
    `httpHost` LowCardinality(String) ALIAS http_host,
    `dbName` LowCardinality(String) ALIAS db_name,
    `dbOperation` LowCardinality(String) ALIAS db_operation,
    `hasError` Bool ALIAS has_error,
    `isRemote` LowCardinality(String) ALIAS is_remote,
    `serviceName` LowCardinality(String) ALIAS `resource_string_service$$name`,
    `httpRoute` LowCardinality(String) ALIAS `attribute_string_http$$route`,
    `msgSystem` LowCardinality(String) ALIAS `attribute_string_messaging$$system`,
    `msgOperation` LowCardinality(String) ALIAS `attribute_string_messaging$$operation`,
    `dbSystem` LowCardinality(String) ALIAS `attribute_string_db$$system`,
    `rpcSystem` LowCardinality(String) ALIAS `attribute_string_rpc$$system`,
    `rpcService` LowCardinality(String) ALIAS `attribute_string_rpc$$service`,
    `rpcMethod` LowCardinality(String) ALIAS `attribute_string_rpc$$method`,
    `peerService` LowCardinality(String) ALIAS `attribute_string_peer$$service`,
    `resource_string_service$$name_exists` Bool DEFAULT if(mapContains(resources_string, 'service.name') != 0, true, false) CODEC(ZSTD(1)),
    `attribute_string_http$$route_exists` Bool DEFAULT if(mapContains(attributes_string, 'http.route') != 0, true, false) CODEC(ZSTD(1)),
    `attribute_string_messaging$$system_exists` Bool DEFAULT if(mapContains(attributes_string, 'messaging.system') != 0, true, false) CODEC(ZSTD(1)),
    `attribute_string_messaging$$operation_exists` Bool DEFAULT if(mapContains(attributes_string, 'messaging.operation') != 0, true, false) CODEC(ZSTD(1)),
    `attribute_string_db$$system_exists` Bool DEFAULT if(mapContains(attributes_string, 'db.system') != 0, true, false) CODEC(ZSTD(1)),
    `attribute_string_rpc$$system_exists` Bool DEFAULT if(mapContains(attributes_string, 'rpc.system') != 0, true, false) CODEC(ZSTD(1)),
    `attribute_string_rpc$$service_exists` Bool DEFAULT if(mapContains(attributes_string, 'rpc.service') != 0, true, false) CODEC(ZSTD(1)),
    `attribute_string_rpc$$method_exists` Bool DEFAULT if(mapContains(attributes_string, 'rpc.method') != 0, true, false) CODEC(ZSTD(1)),
    `attribute_string_peer$$service_exists` Bool DEFAULT if(mapContains(attributes_string, 'peer.service') != 0, true, false) CODEC(ZSTD(1))
)
ENGINE = Distributed('cluster', 'signoz_traces', 'signoz_index_v3', cityHash64(trace_id))
